# Generated by Django 2.2.3 on 2019-07-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_poem_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='Imya',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
