# Generated by Django 2.2.3 on 2019-07-20 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_auto_20190720_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='claim',
            name='like',
        ),
        migrations.AddField(
            model_name='claim',
            name='like',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
