# Generated by Django 2.2.3 on 2019-07-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190720_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='like',
            new_name='likes',
        ),
    ]
